CREATE DATABASE bdLojaJogos;

USE bdLojaJogos;

CREATE TABLE tbFuncionario(
	FuncionarioID SMALLINT PRIMARY KEY,
    Nome VARCHAR(150) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    RG VARCHAR(12) NOT NULL,
    DataNasc DATETIME NOT NULL,
    Endereco VARCHAR(150) NOT NULL,
    Celular VARCHAR(15) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Cargo VARCHAR(50) NOT NULL
);

CREATE TABLE tbJogo(
	JogoID SMALLINT PRIMARY KEY,
    Nome VARCHAR(150) NOT NULL,
    Desenvolvedor VARCHAR(150) NOT NULL,
    Genero VARCHAR(50) NOT NULL,
    FaixaEtaria VARCHAR(10) NOT NULL,
    Plataforma VARCHAR(150) NOT NULL,
    AnoLanc DATETIME NOT NULL,
    Sinopse VARCHAR(300) NOT NULL,
    Versao VARCHAR(10)
);

CREATE TABLE tbCliente(
    CPF VARCHAR(14) PRIMARY KEY,
	Nome VARCHAR(150) NOT NULL,
    DataNasc DATETIME NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Celular VARCHAR(15) NOT NULL,
    Endereco VARCHAR(150) NOT NULL
);